[package]
name = "mtl"
version = "0.1.0"
authors = ["Michael Pedruski <mpedruski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
ndarray = "0.13.1"
rand = "0.7.3"
